version: '3.9'
services:
  company:
    image: kambang/zenou:company
    container_name: company
    depends_on:
      - cache
      - search

  users:
    image: kambang/zenou:users
    container_name: users
    depends_on:
      - cache
      - search

  cache:
    image: redis
    container_name: cache

  search:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.0
    container_name: search
    environment:
      - node.name=search
      - discovery.type=single-node
    ports:
      - 9200:9200
