version: '3.9'

services:
  company:
    image: kambang/zenou:company
    restart: always
    container_name: company
    depends_on:
      # - cache
      - database
      - search

  users:
    image: kambang/zenou:users
    restart: always
    container_name: users
    depends_on:
      # - cache
      - database
      - search

  # cache:
  #   image: redis
  #   container_name: cache

  database:
    image: mongo
    restart: always
    container_name: database
    environment:
      MONGO_INITDB_DATABASE: zenou_db
    volumes:
      - database:/data/db

  mongo-express:
    image: mongo-express
    container_name: database-manager
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://database:27017/

  search:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.0
    container_name: search
    environment:
      - node.name=search
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - search_db:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  proxy:
    container_name: proxy
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 80:80
    volumes:
      - ./nginx.conf/:/etc/nginx/conf.d/default.conf:ro
    restart: always

volumes:
  search_db:
    driver: local
  database:
    driver: local
