version: '3.9'
services:
  company:
    image: kambang/zenou:company
    restart: always
    container_name: company
    depends_on:
      - cache
      - database
      - search

  users:
    image: kambang/zenou:users
    restart: always
    container_name: users
    depends_on:
      - cache
      - database
      - search

  cache:
    image: redis
    container_name: cache
  
  database:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: zenou
      MONGO_INITDB_ROOT_PASSWORD: zenou_admin$C1jo00#!
      MONGO_INITDB_DATABASE: zenou_db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: zenou
      ME_CONFIG_MONGODB_ADMINPASSWORD: zenou_admin$C1jo00#!
      ME_CONFIG_MONGODB_URL: mongodb://zenou:zenou_admin$C1jo00#!@database:27017/zenou_db

  search:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.0
    container_name: search
    environment:
      - node.name=search
      - discovery.type=single-node
    ports:
      - 9200:9200
