name: Deploy Zenou software

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Setting up SSH keys for logging into server
        run: |
          eval "$(ssh-agent -s)"
          ssh-add - <<< "${{ secrets.PRIVATE_KEY }}"
      - name: Deploy Zenou
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SERVER_HOST}}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www/html/application-bootstrap
            git pull origin main
            docker-compose down --remove-orphans
            docker system prune -a -f
            docker-compose up -d